# site settings
title: LibreELEC
subtitle: Just enough OS for KODI
email: youremailaddress@gmail.com
description: Just enough OS for KODI
baseurl: "/massively-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: LibreELEC

# social settings
github_url: https://github.com/LibreELEC/LibreELEC.tv
reddit_url: https://www.reddit.com/r/LibreELEC
twitter_url: https://twitter.com/LibreELEC
youtube_url: https://www.youtube.com/channel/UC7FSO0rXOtO6w_poBLvvjDw

# build settings
markdown: kramdown

sass:
  style: compressed
